config/routes.rb
Rails.application.routes.draw do
  get 'monsters/edit'
  get 'monster/edit'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :monsters
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/monster.rb
class Monster < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  def index
    @Monsters = Monster.all
  end
  
  def show
    @Monster = Monster.find(params[:id])
  end
  
  def new
    @Monster = Monster.new
  end
  
  def create
    @Monster = Monster.new(monster_params)

    if @Monster.save
      redirect_to monsters_path
    else
      render :new
    end
  end
  
  def edit
    @Monster = Monster.find(params[:id])
  end
  
  def update
    @Monster = Monster.find(params[:id])

    if @Monster.update(monster_params)
      redirect_to monsters_path
    else
      render :edit
    end
  end
  
  def destroy
    Monster.find(params[:id]).destroy
    redirect_to monsters_path
  end
  
  private
  
  def monster_params
    params.require(:monster).permit(
      :name, 
      :tags, 
      :ac, 
      :hp, 
      :ground_speed, 
      :fly_speed, 
      :str, 
      :dex, 
      :con, 
      :int, 
      :wis, 
      :cha, 
      :damage_immunity, 
      :condition_immunity, 
      :senses, 
      :languages, 
      :challenge, 
      :action
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/monsters_helper.rb
module MonstersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MonsterManual</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/monsters/edit.html.erb
<h1>Edit Monster</h1>
<%= form_for @Monster do |f| %>
  <%= f.label "Name" %>
  <%= f.text_field :name %>
  <%= f.label "Tags" %>
  <%= f.text_field :tags %>
  <%= f.label "Armor Class" %>
  <%= f.text_field :ac %>
  <%= f.label "HP" %>
  <%= f.text_field :hp %>
  <%= f.label "Ground Speed" %>
  <%= f.text_field :ground_speed%>
  <%= f.label "Fly Speed" %>
  <%= f.text_field :fly_speed %>
  <%= f.label "STR" %>
  <%= f.text_field :str %>
  <%= f.label "DEX" %>
  <%= f.text_field :dex %>
  <%= f.label "CON" %>
  <%= f.text_field :con %>
  <%= f.label "INT" %>
  <%= f.text_field :int %>
  <%= f.label "WIS" %>
  <%= f.text_field :wis %>
  <%= f.label "CHA" %>
  <%= f.text_field :cha %>
  <%= f.label "Damage Immunity" %>
  <%= f.text_field :damage_immunity %>
  <%= f.label "Condition Immunity" %>
  <%= f.text_field :condition_immunity %>
  <%= f.label "Senses" %>
  <%= f.text_field :senses %>
  <%= f.label "Languages" %>
  <%= f.text_field :languages %>
  <%= f.label "Challenge Rating" %>
  <%= f.text_field :challenge %>
  <%= f.label "Actions" %>
  <%= f.text_field :action %>
  <%= f.submit%>
<% end %>

app/views/monsters/index.html.erb
<h1>Monsters</h1>
<p><%= link_to 'Add Monster', new_monster_path %></p>
<% @Monsters.each do |monster| %>
  <h2><%= monster.name%></h2>
  <%= link_to 'View Monster', monster_path(monster) %>
  <%= link_to 'Edit Monster', edit_monster_path(monster) %>
  <%= link_to 'Delete Monster', monster, method: :delete %>
<% end %>

app/views/monsters/new.html.erb
<h1>Add Monster</h1>
<%= form_for @Monster do |f| %>
  <%= f.label "Name" %>
  <%= f.text_field :name %>
  <%= f.label "Tags" %>
  <%= f.text_field :tags %>
  <%= f.label "Armor Class" %>
  <%= f.text_field :ac %>
  <%= f.label "HP" %>
  <%= f.text_field :hp %>
  <%= f.label "Ground Speed" %>
  <%= f.text_field :ground_speed%>
  <%= f.label "Fly Speed" %>
  <%= f.text_field :fly_speed %>
  <%= f.label "STR" %>
  <%= f.text_field :str %>
  <%= f.label "DEX" %>
  <%= f.text_field :dex %>
  <%= f.label "CON" %>
  <%= f.text_field :con %>
  <%= f.label "INT" %>
  <%= f.text_field :int %>
  <%= f.label "WIS" %>
  <%= f.text_field :wis %>
  <%= f.label "CHA" %>
  <%= f.text_field :cha %>
  <%= f.label "Damage Immunity" %>
  <%= f.text_field :damage_immunity %>
  <%= f.label "Condition Immunity" %>
  <%= f.text_field :condition_immunity %>
  <%= f.label "Senses" %>
  <%= f.text_field :senses %>
  <%= f.label "Languages" %>
  <%= f.text_field :languages %>
  <%= f.label "Challenge Rating" %>
  <%= f.text_field :challenge %>
  <%= f.label "Actions" %>
  <%= f.text_field :action %>
  <%= f.submit%>
<% end %>

app/views/monsters/show.html.erb
<h1><%=@Monster.name %></h1>
<p>Tags: <%= @Monster.tags%></p>
<p>Armor Class: <%= @Monster.ac%></p>
<p>HP: <%= @Monster.hp%></p>
<p>Ground Speed: <%= @Monster.ground_speed%></p>
<p>Fly Speed: <%= @Monster.fly_speed%></p>
<p>STR: <%= @Monster.str%></p>
<p>DEX: <%= @Monster.dex%></p>
<p>CON: <%= @Monster.con%></p>
<p>INT: <%= @Monster.int%></p>
<p>WIS: <%= @Monster.wis%></p>
<p>CHA: <%= @Monster.cha%></p>
<p>Damage Immunity: <%= @Monster.damage_immunity%></p>
<p>Condition Immunity: <%= @Monster.condition_immunity%></p>
<p>Senses: <%= @Monster.senses%></p>
<p>Languages: <%= @Monster.languages%></p>
<p>Challenge Rating: <%= @Monster.challenge%></p>
<p>Actions: <%= @Monster.action%></p>